# Generated by Django 5.2.4 on 2025-07-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kpi_objective_keyresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='description',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='current_value',
            field=models.FloatField(default=models.F('start_value')),
        ),
        migrations.AlterField(
            model_name='objective',
            name='quarter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL),
        ),
    ]
