# Generated by Django 5.2.4 on 2025-07-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_objective_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
