# Generated by Django 5.2.4 on 2025-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_objective_description_objective_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
