# Generated by Django 5.2.4 on 2025-08-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_keyresult_current_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='prompt',
            new_name='model_response',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='response',
            new_name='user_prompt',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
